### ISSUE TITLE
UI Problems

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog-plugin-auth-sso#1]
I saw some UI problems with the production artifact.

1) The SSO plugin provider name and description is empty.

![image](https://cloud.githubusercontent.com/assets/461/17149773/0e1e8f3c-536d-11e6-9c63-07c976e5a622.png)

2) The SSO config UI does not show up.

![image](https://cloud.githubusercontent.com/assets/461/17149764/0484868e-536d-11e6-9afd-11961983d800.png)

**Comment by hc4** [comment]
Same problem here.
Tried to send user with default header Remote-User, but no success.

**Comment by kroepke** [comment]
@bernd this has been fixed, right?

**Comment by bernd** [comment]
Yep, works now.

**Comment by hc4** [comment]
does not fixed for me with graylog 2.1.0-beta2 and latest snapshot of sso:
![image](https://cloud.githubusercontent.com/assets/17475270/17366257/e44dcdea-5992-11e6-85f5-a01404cfff1a.png)

**Comment by bernd** [comment]
@hc4 I am unable to reproduce that with 2.1.0-beta.2 and the latest SSO snapshot:

![image](https://cloud.githubusercontent.com/assets/461/17393459/042d1a58-5a24-11e6-932e-f625079d5588.png)

**Comment by hc4** [comment]
Maybe the problem is in my endpoinds config?
```
rest_listen_uri = http://127.0.0.1:80/
rest_transport_uri = http://127.0.0.1:80/
web_listen_uri = http://127.0.0.1:80/web
web_endpoint_uri =
```

I have this erros in console, if I click Update button.
```
Warning: Failed propType: Required prop `id` was not specified in `SortableListItem`. Check the render method of `DragSource(SortableListItem)
Warning: Failed propType: Required prop `text` was not specified in `SortableListItem`. Check the render method of `DragSource(SortableListItem)
```

**Comment by hc4** [comment]
Or maybe I just incorrectly built this plugin :)
Where can I download binary?

**Comment by hc4** [comment]
Ok. Problem solved.
The cause was, that I removed web-interface-build section from pom.xml

Funny that without that section plugin jar size is 17KB, but with this sections it is 400KB
